/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSegmentsRouteImport } from './routes/_authenticated/segments'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCustomersRouteImport } from './routes/_authenticated/customers'
import { Route as AuthenticatedChatRouteImport } from './routes/_authenticated/chat'
import { Route as AuthenticatedCampaignsRouteImport } from './routes/_authenticated/campaigns'
import { Route as ApiPublicVendorSendRouteImport } from './routes/api/public/vendor.send'
import { Route as ApiPublicIngestOrdersRouteImport } from './routes/api/public/ingest.orders'
import { Route as ApiPublicIngestCustomersRouteImport } from './routes/api/public/ingest.customers'
import { Route as ApiPublicCrmReceiptRouteImport } from './routes/api/public/crm.receipt'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSegmentsRoute = AuthenticatedSegmentsRouteImport.update({
  id: '/segments',
  path: '/segments',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCustomersRoute = AuthenticatedCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChatRoute = AuthenticatedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCampaignsRoute = AuthenticatedCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicVendorSendRoute = ApiPublicVendorSendRouteImport.update({
  id: '/api/public/vendor/send',
  path: '/api/public/vendor/send',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicIngestOrdersRoute = ApiPublicIngestOrdersRouteImport.update({
  id: '/api/public/ingest/orders',
  path: '/api/public/ingest/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicIngestCustomersRoute =
  ApiPublicIngestCustomersRouteImport.update({
    id: '/api/public/ingest/customers',
    path: '/api/public/ingest/customers',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCrmReceiptRoute = ApiPublicCrmReceiptRouteImport.update({
  id: '/api/public/crm/receipt',
  path: '/api/public/crm/receipt',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/campaigns': typeof AuthenticatedCampaignsRoute
  '/chat': typeof AuthenticatedChatRoute
  '/customers': typeof AuthenticatedCustomersRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/segments': typeof AuthenticatedSegmentsRoute
  '/api/public/crm/receipt': typeof ApiPublicCrmReceiptRoute
  '/api/public/ingest/customers': typeof ApiPublicIngestCustomersRoute
  '/api/public/ingest/orders': typeof ApiPublicIngestOrdersRoute
  '/api/public/vendor/send': typeof ApiPublicVendorSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/campaigns': typeof AuthenticatedCampaignsRoute
  '/chat': typeof AuthenticatedChatRoute
  '/customers': typeof AuthenticatedCustomersRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/segments': typeof AuthenticatedSegmentsRoute
  '/api/public/crm/receipt': typeof ApiPublicCrmReceiptRoute
  '/api/public/ingest/customers': typeof ApiPublicIngestCustomersRoute
  '/api/public/ingest/orders': typeof ApiPublicIngestOrdersRoute
  '/api/public/vendor/send': typeof ApiPublicVendorSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/campaigns': typeof AuthenticatedCampaignsRoute
  '/_authenticated/chat': typeof AuthenticatedChatRoute
  '/_authenticated/customers': typeof AuthenticatedCustomersRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/segments': typeof AuthenticatedSegmentsRoute
  '/api/public/crm/receipt': typeof ApiPublicCrmReceiptRoute
  '/api/public/ingest/customers': typeof ApiPublicIngestCustomersRoute
  '/api/public/ingest/orders': typeof ApiPublicIngestOrdersRoute
  '/api/public/vendor/send': typeof ApiPublicVendorSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/campaigns'
    | '/chat'
    | '/customers'
    | '/dashboard'
    | '/segments'
    | '/api/public/crm/receipt'
    | '/api/public/ingest/customers'
    | '/api/public/ingest/orders'
    | '/api/public/vendor/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/campaigns'
    | '/chat'
    | '/customers'
    | '/dashboard'
    | '/segments'
    | '/api/public/crm/receipt'
    | '/api/public/ingest/customers'
    | '/api/public/ingest/orders'
    | '/api/public/vendor/send'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/campaigns'
    | '/_authenticated/chat'
    | '/_authenticated/customers'
    | '/_authenticated/dashboard'
    | '/_authenticated/segments'
    | '/api/public/crm/receipt'
    | '/api/public/ingest/customers'
    | '/api/public/ingest/orders'
    | '/api/public/vendor/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicCrmReceiptRoute: typeof ApiPublicCrmReceiptRoute
  ApiPublicIngestCustomersRoute: typeof ApiPublicIngestCustomersRoute
  ApiPublicIngestOrdersRoute: typeof ApiPublicIngestOrdersRoute
  ApiPublicVendorSendRoute: typeof ApiPublicVendorSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/segments': {
      id: '/_authenticated/segments'
      path: '/segments'
      fullPath: '/segments'
      preLoaderRoute: typeof AuthenticatedSegmentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customers': {
      id: '/_authenticated/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AuthenticatedCustomersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chat': {
      id: '/_authenticated/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthenticatedChatRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/campaigns': {
      id: '/_authenticated/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof AuthenticatedCampaignsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/vendor/send': {
      id: '/api/public/vendor/send'
      path: '/api/public/vendor/send'
      fullPath: '/api/public/vendor/send'
      preLoaderRoute: typeof ApiPublicVendorSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ingest/orders': {
      id: '/api/public/ingest/orders'
      path: '/api/public/ingest/orders'
      fullPath: '/api/public/ingest/orders'
      preLoaderRoute: typeof ApiPublicIngestOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ingest/customers': {
      id: '/api/public/ingest/customers'
      path: '/api/public/ingest/customers'
      fullPath: '/api/public/ingest/customers'
      preLoaderRoute: typeof ApiPublicIngestCustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/crm/receipt': {
      id: '/api/public/crm/receipt'
      path: '/api/public/crm/receipt'
      fullPath: '/api/public/crm/receipt'
      preLoaderRoute: typeof ApiPublicCrmReceiptRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCampaignsRoute: typeof AuthenticatedCampaignsRoute
  AuthenticatedChatRoute: typeof AuthenticatedChatRoute
  AuthenticatedCustomersRoute: typeof AuthenticatedCustomersRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedSegmentsRoute: typeof AuthenticatedSegmentsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCampaignsRoute: AuthenticatedCampaignsRoute,
  AuthenticatedChatRoute: AuthenticatedChatRoute,
  AuthenticatedCustomersRoute: AuthenticatedCustomersRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedSegmentsRoute: AuthenticatedSegmentsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicCrmReceiptRoute: ApiPublicCrmReceiptRoute,
  ApiPublicIngestCustomersRoute: ApiPublicIngestCustomersRoute,
  ApiPublicIngestOrdersRoute: ApiPublicIngestOrdersRoute,
  ApiPublicVendorSendRoute: ApiPublicVendorSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
